version: "3.8"

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - log-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s

  fluent-bit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fluent-bit
    networks:
      - log-network

  vector:
    image: timberio/vector:0.33.0-debian
    container_name: vector
    volumes:
      - ./vector.yaml:/etc/vector/vector.yaml:ro
      #- ./vector-logs:/tmp/vector-logs  # Mapeia a pasta de logs para o host
    networks:
      - log-network
    depends_on:
      localstack:
        condition: service_healthy
      fluent-bit:
        condition: service_started
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test

networks:
  log-network:
    driver: bridge

